### ISSUE TITLE
How to solve 410 Gone (RestClient::Gone)

### ISSUE THREAD

**Issue by yagoangelo** [anildigital/doesfollow#1]
I need to integrate 'doesfollow' with another application, but i'm facing this error:

/var/lib/gems/1.9.1/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 410 Gone (RestClient::Gone)
    from /var/lib/gems/1.9.1/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in`process_result'
    from /var/lib/gems/1.9.1/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
    from /usr/lib/ruby/1.9.1/net/http.rb:746:in`start'
    from /var/lib/gems/1.9.1/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
    from /var/lib/gems/1.9.1/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in`execute'
    from /var/lib/gems/1.9.1/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
    from /var/lib/gems/1.9.1/gems/rest-client-1.8.0/lib/restclient.rb:65:in`get'
    from /var/lib/gems/1.9.1/gems/doesfollow-0.4.0/lib/doesfollow.rb:46:in `get_resource_json'
    from /var/lib/gems/1.9.1/gems/doesfollow-0.4.0/lib/doesfollow.rb:41:in`get_friendship_json'
    from /var/lib/gems/1.9.1/gems/doesfollow-0.4.0/lib/doesfollow.rb:36:in `get_doesfollow_status'
    from /var/lib/gems/1.9.1/gems/doesfollow-0.4.0/lib/doesfollow.rb:28:in`doesfollow'
    from /var/lib/gems/1.9.1/gems/doesfollow-0.4.0/bin/doesfollow:23:in `<top (required)>'
    from /usr/local/bin/doesfollow:23:in`load'
    from /usr/local/bin/doesfollow:23:in `<main>'

I got no ideia how to solve it.

**Comment by anildigital** [comment]
@frigids-PUCC Fix is coming this weekend. I will notify you. Thanks.
